<?php
/**
 * @link      http://www.activemedia.uz/
 * @copyright Copyright (c) 2017. ActiveMedia Solutions LLC
 * @author    Rustam Mamadaminov <rmamdaminov@gmail.com>
 */

namespace backend\controllers;

use common\components\Config;
use common\components\CropUpload;
use common\models\Post;
use common\models\Tag;
use MongoDB\BSON\ObjectID;
use Yii;
use yii\base\Exception;
use yii\base\InvalidArgumentException;
use yii\base\InvalidParamException;
use yii\mongodb\ActiveRecord;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

class PostController extends BackendController
{
    public $activeMenu = 'store';

    public function actions()
    {
        return [
            'upload' => [
                'class'            => CropUpload::className(),
                'deleteRoute'      => 'delete',
                'responseUrlParam' => 'location',
                'on afterSave'     => function ($event) {
                    /* @var $file \League\Flysystem\File */
                    $file = $event->file;
                    // do something (resize, add watermark etc)
                },
            ],
            'delete' => [
                'class' => 'common\components\CropUploadDelete',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->request->isAjax) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $query
     * @return string[]
     * @resource News | Manage Posts | post/tag
     */
    public function actionTag($query)
    {
        /**
         * @var $tag Tag
         */
        Yii::$app->response->format = Response::FORMAT_JSON;

        $tags = Tag::find()
                   ->select(['name_uz', 'name_cy', 'name_ru', 'count', 'slug'])
                   ->orderBy(['count' => SORT_DESC])
                   ->limit(20);

        if ($query) {
            $tags->orFilterWhere(['name_uz' => ['$regex' => $query, '$options' => 'si']]);
            $tags->orFilterWhere(['name_ru' => ['$regex' => $query, '$options' => 'si']]);
            $tags->orFilterWhere(['name_cy' => ['$regex' => $query, '$options' => 'si']]);
        }

        $result = [];

        foreach ($tags->all() as $tag) {
            $result[] = [
                'v' => $tag->getId(),
                't' => $tag->name,
            ];
        }
        return $result;
    }

    /**
     * @param bool|string $type
     * @return string
     * @resource News | Manage Posts | post/index,post/upload
     */
    public function actionIndex($type = false)
    {
        $searchModel = new Post(['scenario' => 'search']);
        if ($type && !isset(Post::getTypeArray()[$type])) {
            throw new InvalidArgumentException("Undefined type '$type'");
        }
        if ($type) {
            $searchModel->post_type = $type;
        }
        return $this->render('index', [
            'dataProvider' => $searchModel->search($this->get()),
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * @return string
     * @resource News |  Manage Posts | post/draft
     */
    public function actionDraft()
    {
        $searchModel         = new Post(['scenario' => 'search']);
        $searchModel->status = Post::STATUS_DRAFT;

        return $this->render('index', [
            'dataProvider' => $searchModel->search($this->get()),
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * @return string
     * @resource News |  Manage Posts | post/photo
     */
    public function actionPhoto()
    {
        return $this->actionIndex(Post::TYPE_GALLERY);
    }

    /**
     * @return string
     * @resource News |  Manage Posts | post/video
     */
    public function actionVideo()
    {
        return $this->actionIndex(Post::TYPE_VIDEO);
    }

    /**
     * @param $type
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @resource News | Manage Posts | post/create,file-storage/delete,file-storage/upload
     */
    public function actionCreate($type)
    {
        if (!isset(Post::getTypeArray()[$type])) {
            throw new NotFoundHttpException(__("Undefined type '$type'"));
        }
        $model = new Post(['scenario' => 'create']);

        $model->type = $type;
        if ($model->updatePost()) {
            $this->addSuccess(__('Post {type} created successfully', ['type' => $model->getTypeLabel()]));

            return $this->redirect(['edit', 'id' => $model->getId()]);
        }
    }

    /**
     * @param $id
     * @return array|string|Response
     * @resource News | Manage Posts | post/edit,tag/fetch
     */
    public function actionEdit($id)
    {
        $model = $this->findModel($id);

        $model->scenario = $model->type;

        if ($model->status != Post::STATUS_IN_TRASH) {
            if ($this->get('save') && Yii::$app->request->isAjax) {
                if (isset($_POST['Post']['content'])) {
                    $model->content = $_POST['Post']['content'];
                    $model->updatePost();
                    return 1;
                }
            }
            if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $model->save();

                return ActiveForm::validate($model);
            }


            if ($this->get('convert')) {
                $changed = false;
                $lang    = Yii::$app->language;

                if ($lang == Config::LANGUAGE_CYRILLIC) {
                    $changed = $model->convertToLatin();

                    $lang = Config::LANGUAGE_UZBEK;
                } else if ($lang == Config::LANGUAGE_UZBEK) {
                    $changed = $model->convertToCyrillic();

                    $lang = Config::LANGUAGE_CYRILLIC;
                }

                if ($changed) {
                    $this->addSuccess(__('Post converted to {language} successfully', ['language' => Config::getLanguageLabel($lang)]));
                }

                return $this->redirect(['edit', 'id' => $model->getId(), 'language' => $lang]);
            }

            if ($model->load(Yii::$app->request->post())) {
                if ($model->updatePost()) {
                    if ($id) {
                        $this->addSuccess(__('Post {title} updated successfully', ['title' => $model->getTitleView()]));
                    } else {
                        $this->addSuccess(__('Post {title} created successfully', ['title' => $model->getTitleView()]));
                    }

                    return $this->redirect(['edit', 'id' => $model->getId()]);
                } else {
                    foreach ($model->getErrors() as $errors) {
                        foreach ($errors as $error) {
                            $this->addError($error);
                        }
                    }
                }

            }
        }

        return $this->render('edit', [
            'model' => $model,
            'type'  => $model->type,
        ]);
    }

    /**
     * @param $id
     * @return array
     * @resource News | Share Posts | post/share
     */
    public function actionShare($id)
    {
        $model  = $this->findModel($id);
        $social = $this->post('sharer');
        $result = false;
        if (isset(Post::getSocialArray()[$social])) {
            $result = $model->shareTo($social);
        }

        Yii::$app->response->format = Response::FORMAT_JSON;
        return ['success' => $result];
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @resource News | Trash Posts | post/trash
     */
    public function actionTrash($id)
    {
        $model = $this->findModel($id);

        if ($model->toTrash()) {

            $this->addSuccess(__('Post {title} moved to trash successfully', ['title' => $model->getTitleView()]));
            return $this->redirect(Yii::$app->request->isAjax ? Yii::$app->request->getReferrer() : '/post/index');
        }

        $this->addError(__('Post {title} moved to trash failed', ['title' => $model->getTitleView()]));
        return $this->redirect(['edit', 'id' => $model->getId()]);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @resource News | Send Push Notification | post/notification
     */
    public function actionNotification($id)
    {
        $model = $this->findModel($id);

        try {
            if ($model->sendPushNotification()) {
                $this->addSuccess(__('Push notification "{title}" sent successfully', ['title' => $model->getTitleView()]));
            } else {
            }
        } catch (\Exception $e) {
            $this->addError($e->getMessage());
        }


        return $this->redirect(['edit', 'id' => $model->getId()]);
    }

    /**
     * @param $id
     * @param $attribute
     * @resource News | Manage Posts | post/change
     * @return bool
     */
    public function actionChange($id, $attribute)
    {
        $post = $this->findModel($id);
        if ($post->hasAttribute($attribute)) {
            if ($post->$attribute) {
                $post->$attribute = false;
                $post->save(false);
            } else {
                $post->$attribute = true;
                $post->save(false);
            }
            return !$post->hasErrors();
        }
        return false;
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @resource System | View Trash | post/restore
     */
    public function actionRestore($id)
    {
        $model = $this->findModel($id);

        if ($model->restoreFromTrash()) {
            $this->addSuccess(__('Post {title} restored successfully', ['title' => $model->getTitleView()]));
        }

        return $this->redirect(['post/edit', 'id' => $model->getId()]);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @resource News | Delete Post | post/delete
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        try {
            if ($model->delete()) {

                $this->addSuccess(__('Post {title} moved to trash successfully', ['title' => $model->getTitleView()]));
            }
        } catch (Exception $e) {
            $this->addError($e->getMessage());

            return $this->redirect(['edit', 'id' => $model->getId()]);
        }


        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return null|Post|ActiveRecord
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne(new ObjectID($id))) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested post does not exist.');
        }
    }

}
