<?php

namespace frontend\components;

use common\models\User;
use frontend\controllers\BaseController;
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\IdentityInterface;

class View extends \yii\web\View
{

    protected $_user        = null;
    protected $_bodyClass   = [];
    protected $_canonical;
    protected $_image;
    protected $_keywords    = [];
    protected $_description = [];
    /**
     * @var  ContextInterface|BaseController
     */
    public $context;

    public function init()
    {
        parent::init();
    }

    public function beforeRender($viewFile, $params)
    {
        return parent::beforeRender($viewFile, $params); // TODO: Change the autogenerated stub
    }


    public function hasKeywords()
    {
        $this->_keywords = array_filter($this->_keywords, function ($item) {
            return $item ? true : false;
        });

        return count($this->_keywords) > 0;
    }

    public function hasDescription()
    {
        $this->_description = array_filter($this->_description, function ($item) {
            return $item ? true : false;
        });

        return count($this->_description) > 0;
    }

    public function addKeywords($keywords)
    {
        $this->_keywords = array_merge($this->_keywords, $keywords);
    }

    public function addDescription($description)
    {
        $this->_description = array_merge($this->_description, $description);
    }

    public function getKeywords()
    {

        $this->_keywords = array_filter($this->_keywords, function ($item) {
            return $item ? true : false;
        });


        return Html::encode(implode(', ', $this->_keywords));
    }

    public function getDescription()
    {
        $this->_description = array_filter($this->_description, function ($item) {
            return trim($item) ? true : false;
        });

        array_walk($this->_description, function (&$item) {
            $item = trim($item, '.');
        });

        return Html::encode(implode(' ', $this->_description));
    }


    public function getCanonical()
    {
        return $this->_canonical ? $this->_canonical : Url::to(['/' . $this->getFullActionName()], true);
    }

    public function getImage()
    {
        if ($this->_image) {
            return $this->_image;
        } else if (isset($this->params['post'])) {
            /**
             * @var $post PostProvider
             */
            $post = $this->params['post'];
            return $post->getImage(736, 736, false);
        }
        return $this->getImageUrl('saxovat-qoqon.png');
    }

    /**
     * @return IdentityInterface|User
     */
    public function getUser()
    {
        if (!Yii::$app->user->isGuest && $this->_user === null) {
            $this->_user = Yii::$app->user->identity;
        }
        return $this->_user;
    }

    public function url($data)
    {
        return Yii::$app->urlManager->createUrl($data);
    }

    public function getImageUrl($name)
    {
        return $this->getAssetManager()->getBundle('frontend\assets\AppAsset')->baseUrl . '/images/' . $name;
    }

    public function getBodyClass()
    {
        return implode(' ', $this->_bodyClass);
    }

    public function getFullActionName()
    {
        $this->_bodyClass[] = Yii::$app->controller->id . '_' . Yii::$app->controller->action->id;
        return Yii::$app->controller->id . '/' . Yii::$app->controller->action->id;
    }

}