<?php
/**
 * @link      http://www.activemedia.uz/
 * @copyright Copyright (c) 2018. ActiveMedia Solutions LLC
 * @author    Rustam Mamadaminov <rmamdaminov@gmail.com>
 */

/**
 * Created by PhpStorm.
 * User: rustam
 * Date: 3/18/17
 * Time: 11:38 AM
 */

namespace common\models;


use common\components\Config;
use MongoDB\BSON\ObjectID;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;

/**
 * @property string fullname
 * @property string status
 * @property string description
 * @property string content
 * @property string birthday
 * @property array image
 * @property mixed _search
 * @property mixed _category
 *
 * @property Project project
 */
class Patient extends MongoModel
{
    protected $_translatedAttributes = ['fullname', 'address', 'diagnose', 'description', 'content'];
    protected $_idAttributes         = ['_project'];

    public static function getStatusOptions()
    {
        return [
            0 => __('Yordam kerak'),
            1 => __('Yordam berildi'),
        ];
    }

    public function getStatusLabel()
    {
        $options = self::getStatusOptions();
        return isset($options[$this->status]) ? $options[$this->status] : $this->status;
    }

    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return 'patient';
    }

    public static function getAll()
    {
        $all = self::find()->all();
        return ArrayHelper::map($all, 'id', 'name');
    }

    public function attributes()
    {
        return array_merge(parent::attributes(), [
            'fullname',
            'status',
            'birthday',
            'content',
            'description',
            '_project',
            'diagnose',
            'address',
            'image',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fullname', 'birthday', 'diagnose', 'address', 'image'], 'required'],
            [['fullname'], 'string', 'max' => 128],
            [['content', 'image', '_project', 'description'], 'safe'],
            [['search'], 'safe', 'on' => 'search'],
        ];
    }

    /**
     * @return \yii\db\ActiveQueryInterface
     */
    public function getProject()
    {
        return $this->hasOne(Project::class, ['_id' => '_project']);
    }

    public function search($params = [])
    {
        $query = self::find();
        $this->load($params);

        $dataProvider = new ActiveDataProvider([
                                                   'query'      => $query,
                                                   'sort'       => [
                                                       'defaultOrder' => [
                                                           'created_at' => SORT_DESC,
                                                       ],
                                                       'attributes'   => [
                                                           'fullname',
                                                           'created_at',
                                                           'birthday',
                                                       ],
                                                   ],
                                                   'pagination' => [
                                                       'pageSize' => 50,
                                                   ],
                                               ]);

        if ($this->search) {
            $query->andFilterWhere(['like', 'fullname', $this->search]);
            $query->andFilterWhere(['like', 'diagnose', $this->search]);
        }

        return $dataProvider;
    }

    public function afterFind()
    {
        parent::afterFind();
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}