<?php
/**
 * @link      http://www.activemedia.uz/
 * @copyright Copyright (c) 2018. ActiveMedia Solutions LLC
 * @author    Rustam Mamadaminov <rmamdaminov@gmail.com>
 */

namespace common\models;

use common\components\Config;
use MongoDB\BSON\ObjectID;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;

/**
 * @property string name
 * @property string status
 * @property string description
 * @property string content
 * @property array image
 * @property mixed _search
 * @property mixed _category
 *
 * @property Category category
 */
class Project extends MongoModel
{
    protected $_translatedAttributes = ['name', 'description', 'content'];

    const STATUS_ENABLE  = 'enable';
    const STATUS_DISABLE = 'disable';

    public static function getStatusOptions()
    {
        return [
            self::STATUS_ENABLE  => __('Enable'),
            self::STATUS_DISABLE => __('Disable'),
        ];
    }

    public function getStatusLabel()
    {
        $options = self::getStatusOptions();
        return isset($options[$this->status]) ? $options[$this->status] : $this->status;
    }

    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return 'project';
    }

    public static function getAll()
    {
        $all = self::find()->all();
        return ArrayHelper::map($all, 'id', 'name');
    }

    public static function getProjectsAsOption()
    {
        $result = ArrayHelper::map(self::find()->select(['_id', 'name'])->orderBy('name')->all(), function (self $model) {
            return $model->getId();
        }, 'name');
        return $result;
    }

    public function attributes()
    {
        return array_merge(parent::attributes(), [
            'name',
            'status',
            'content',
            'description',
            'image',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 128],
            [['content', 'image', 'description', 'status'], 'safe'],
            [['search'], 'safe', 'on' => 'search'],
        ];
    }

    public function search($params = [])
    {
        $query = self::find();
        $this->load($params);

        $dataProvider = new ActiveDataProvider([
                                                   'query'      => $query,
                                                   'sort'       => [
                                                       'defaultOrder' => [
                                                           'created_at' => SORT_DESC,
                                                       ],
                                                       'attributes'   => [
                                                           'name',
                                                           'created_at',
                                                           'start_time',
                                                       ],
                                                   ],
                                                   'pagination' => [
                                                       'pageSize' => 50,
                                                   ],
                                               ]);

        if ($this->search) {
            $query->andFilterWhere(['like', 'name', $this->search]);
        }

        return $dataProvider;
    }

    public function afterFind()
    {
        parent::afterFind();
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}