<?php

namespace frontend\assets;

use yii\web\AssetBundle;

/**
 * Main frontend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $sourcePath = '@app/assets/app';
    public $css        = [
        'vendor/bootstrap/css/bootstrap.min.css',
        'css/fontello.css',
        'css/fontello-ie7.css',
        'css/theme.css',
        'css/custom-style.css',
    ];
    public $js         = [
        'vendor/popper/popper.min.js',
        'vendor/bootstrap/js/bootstrap.min.js',
        'js/jquery.formatter.min.js',
        'js/custom.js',
    ];
    public $depends    = [
        'yii\web\YiiAsset',
        'yii\web\JqueryAsset',
    ];

    public function init()
    {
        if (ASSET_BUNDLE) {
            $this->depends = [];
            $this->js      = ['js/app.min.js'];
            $this->css     = ['css/app.min.css'];
        }
        parent::init(); // TODO: Change the autogenerated stub
    }


}
