<?php

use api\components\ResponseFormatterXml;

$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'api\controllers',
    'bootstrap' => ['log', 'config'],
    'modules' => [],
    'components' => [
        'response' => [
            'class' => 'yii\web\Response',
            'format' => yii\web\Response::FORMAT_JSON,
            'formatters' => [
                yii\web\Response::FORMAT_XML => ResponseFormatterXml::className(),
            ],
            'on beforeSend' => [
                'api\components\RequestLogger',
                'logRequest',
            ],
        ],
        'request' => [
            'enableCookieValidation' => false,
            'enableCsrfValidation' => false,
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
        ],
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                'v1/<controller:\w+>/<action:\w+>' => 'v1/<controller>/<action>',
                'v1/<controller:\w+>/<action:list>/<page:\d+>/?' => 'v1/<controller>/<action>',

                'v1/paycom' => 'v1/paycom/index',
                'v1/click' => 'v1/click/index',
                'v1/paymo' => 'v1/paymo/index',
                'paymo' => 'v1/paymo/index',
                'paynet' => 'v1/paynet/index',
                'kapital' => 'v1/kapital/index',
            ],
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 3,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['kapital'],
                    'logFile' => '@app/runtime/logs/kapital.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['paynet'],
                    'logFile' => '@app/runtime/logs/paynet.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['apelsin'],
                    'logFile' => '@app/runtime/logs/apelsin.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['paycom'],
                    'logFile' => '@app/runtime/logs/paycom.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['click'],
                    'logFile' => '@app/runtime/logs/click.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'categories' => ['application', 'request'],
                    'logVars' => ['_GET', '_POST'],
                    'logFile' => '@app/runtime/logs/app.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'categories' => ['api'],
                    'logVars' => ['_GET', '$_POST'],
                    'logFile' => '@app/runtime/logs/api.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'categories' => ['paymo'],
                    'logVars' => ['_GET', '$_POST'],
                    'logFile' => '@app/runtime/logs/paymo.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace'],
                    'enabled' => YII_DEBUG,
                    'logVars' => [],
                    'categories' => ['agr'],
                    'logFile' => '@app/runtime/logs/agr.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['trace'],
                    'enabled' => true,
                    'logVars' => [],
                    'categories' => ['agr_trace'],
                    'logFile' => '@app/runtime/logs/agr_trace.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 200,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error'],
                    'enabled' => true,
                    'logVars' => [],
                    'categories' => ['paycom', 'click', 'paynet', 'kapital', 'paymo', 'upay', 'apelsin'],
                    'logFile' => '@app/runtime/logs/payment_error.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error'],
                    'enabled' => true,
                    'logVars' => [],
                    'categories' => ['request'],
                    'logFile' => '@app/runtime/logs/request_error.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error'],
                    'enabled' => true,
                    'logVars' => ['$_POST'],
                    'categories' => ['application'],
                    'logFile' => '@app/runtime/logs/runtime_error.log',
                    'maxFileSize' => 1024 * 2,
                    'maxLogFiles' => 20,
                ],
            ],
        ],
    ],

    'params' => $params,
];
