<?php
/**
 * @link      http://www.activemedia.uz/
 * @copyright Copyright (c) 2018. ActiveMedia Solutions LLC
 * @author    Rustam Mamadaminov <rmamdaminov@gmail.com>
 */

/**
 * Created by PhpStorm.
 * Date: 12/12/17
 * Time: 12:22 AM
 */

namespace frontend\widgets;


use frontend\components\ContextInterface;
use frontend\components\View;
use yii\base\Widget;
use yii\web\IdentityInterface;
use yii\web\Response;
use yii\web\User;

/**
 * Class BaseWidget
 * @package frontend\widgets
 * @property View $view
 */
class BaseWidget extends Widget implements ContextInterface
{
    public  $emptyText;
    private $_user;

    public function getImageUrl($name)
    {
        return $this->getView()->getImageUrl($name);
    }

    /**
     * @return User|IdentityInterface|Response
     */
    public function _user()
    {
        if (!\Yii::$app->user->isGuest && !$this->_user) {
            $this->_user = \Yii::$app->user->identity;
            if ($this->_user == null) {
                \Yii::$app->user->logout();

                return $this->getView()->context->goHome();
            }
        }

        return $this->_user;

    }

    /**
     * @return View|\yii\web\View
     */
    public function getView()
    {
        return parent::getView(); // TODO: Change the autogenerated stub
    }
}